export const constants = {
    GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
    GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',
    GET_CONTACT_PHONES_SUCCES: 'GET_CONTACT_PHONES_SUCCES',
    GET_CONTACT_PHONES_ERROR: 'GET_CONTACT_PHONES_ERROR',
    POST_CREATE_CONTACT_SUCCES: 'POST_CREATE_CONTACT_SUCCES',
    POST_CREATE_CONTACT_ERROR: 'POST_CREATE_CONTACT_ERROR'
}